# Setup

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="2"
os.environ["CUDA_LAUNCH_BLOCKING"]="1, 2, 3, 4"

In [2]:
import numpy as np
import pandas as pd

from sklearn.metrics.pairwise import cosine_similarity

In [3]:
import torch
from sklearn.preprocessing import normalize
from torch.utils.data import Dataset, DataLoader
from torchsampler import ImbalancedDatasetSampler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import f1_score, precision_score, recall_score

# Import Data

In [4]:
items = pd.read_csv("../Datasets/ml-100k/Text/items.csv")

r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('../Datasets/ml-100k/Text/u1.base', sep='\t', names=r_cols,encoding='latin-1')

In [5]:
# n_users = ratings.user_id.unique().shape[0]
# n_items = ratings.movie_id.unique().shape[0]
n_users = 943
n_items = 1682

In [6]:
data_matrix = np.zeros((n_users, n_items))
for line in ratings.itertuples():
    data_matrix[line[1]-1, line[2]-1] = line[3]

In [7]:
data_matrix_emp = data_matrix.copy()
data_matrix_emp[data_matrix < 4] = 0
data_matrix_emp[data_matrix >= 4]= 1 

In [8]:
train_indices = list(zip(*(np.where(data_matrix != 0))))

In [9]:
len(train_indices)

80000

# Siamese network

## Data loader

In [10]:
torch.cuda.is_available()

True

In [11]:
torch.__version__

'1.10.1'

In [12]:
items_csv = "../Datasets/ml-100k/Text/items.csv"
train_ratings = "../Datasets/ml-100k/Text/u1.base"
test_ratings = "../Datasets/ml-100k/Text/u1.test"

item_path = "../Datasets/ml-100k/"

In [13]:
# cosine_similarity(np.nan_to_num(pd.read_csv(item_path)))

In [14]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [15]:
class MovielensDataset(Dataset):
    def __init__(self, ratings = train_ratings, item_path = item_path, device = device):
        self.video_embeddings = pd.read_csv(item_path + "Video/embeddings.csv").to_numpy()
        self.audio_embeddings = pd.read_csv(item_path + "Audio/embeddings.csv").to_numpy()
        self.text_embeddings = pd.read_csv(item_path + "Meta/embeddings.csv").to_numpy()
        self.ratings = pd.read_csv(ratings, sep='\t', 
                                   names=['user_id', 'movie_id', 'rating', 'unix_timestamp'],encoding='latin-1')
        self.indices = None
        self.device = device
        self.data = None
        self.n_users = None
        self.n_items = None
        self.fill_ratings()
        self.embeddings()
    
    def fill_ratings(self, threshold=4):
        self.n_users = self.ratings.user_id.unique().shape[0]
        self.n_items = self.ratings.movie_id.unique().shape[0]
        
        self.data = np.zeros((n_users, n_items))
        for line in self.ratings.itertuples():
            self.data[line[1]-1, line[2]-1] = line[3]
            
        self.indices = list(zip(*(np.where(self.data != 0))))
            
    def embeddings(self):
        self.audio_embeddings = np.nan_to_num(self.audio_embeddings)
        self.video_embeddings = np.nan_to_num(self.video_embeddings)
        self.audio_embeddings = normalize(self.audio_embeddings, axis = 1)
#         self.item_embeddings = np.append(data_matrix.T, self.item_embeddings, axis = 1)
        self.user_embeddings = data_matrix
        self.item_embeddings = data_matrix.T
        self.video_embedding_size = self.video_embeddings.shape[1]
        self.audio_embedding_size = self.audio_embeddings.shape[1]
        self.text_embedding_size = self.text_embeddings.shape[1]
        self.user_embedding_size = self.user_embeddings.shape[1]
        self.item_embedding_size = self.item_embeddings.shape[1]
        
    def __len__(self):
        return(len(self.indices))
    
    def __getitem__(self, idx):
        user = self.indices[idx][0]
        item = self.indices[idx][1]

        xu = torch.from_numpy(self.user_embeddings[user]).to(self.device)
        xv = torch.from_numpy(self.video_embeddings[item]).to(self.device)
        xa = torch.from_numpy(self.audio_embeddings[item]).to(self.device)
        xt = torch.from_numpy(self.text_embeddings[item]).to(self.device)
        xi = torch.from_numpy(self.item_embeddings[item]).to(self.device)
        
        y = self.data[user][item]
        return(xu.float(), [xv.float(), xa.float(), xt.float(), xi.float()], int(y))

In [16]:
train_dataset = MovielensDataset(ratings = train_ratings)
test_dataset = MovielensDataset(ratings = test_ratings)

/home/sriram_1801cs37/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/sriram_1801cs37/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/sriram_1801cs37/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/sriram_1801cs37/anaconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [17]:
target = [int(data_matrix[train_dataset.indices[i][0]][train_dataset.indices[i][1]]) - 1 for i in range(len(train_dataset))]

In [18]:
class_sample_count = np.unique(data_matrix, return_counts=True)[1][1::]

weights = 1 / torch.Tensor(class_sample_count)
weights = weights.double()
weights_all = weights[target]

In [19]:
sampler = torch.utils.data.sampler.WeightedRandomSampler(weights_all, len(weights_all))

In [20]:
trainloader = DataLoader(train_dataset, batch_size = 30000, shuffle = True)
testloader = DataLoader(test_dataset, batch_size = 20000, shuffle = False)

## Architecture

In [21]:
from tqdm import tqdm
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from collections import OrderedDict

In [22]:
from ml_metrics import mapk
from recmetrics import mark

In [23]:
class SiameseNet(nn.Module):
    def __init__(self, device = device):
        super(SiameseNet, self).__init__()
        self.encoder_user = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(train_dataset.user_embedding_size, 1024)),
            ('relu1', nn.LeakyReLU()),
            ('linr2', nn.Linear(1024, 200)),
            ('relu2', nn.LeakyReLU()),
#             ('linr3', nn.Linear(800, 500)),
#             ('relu3', nn.LeakyReLU()),
#             ('linr4', nn.Linear(500, 600)),
#             ('relu4', nn.LeakyReLU()),
        ]))
        
        self.encoder_item = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(train_dataset.item_embedding_size, 256)),
            ('relu1', nn.Sigmoid()),
            ('linr2', nn.Linear(256, 200)),
            ('relu2', nn.LeakyReLU()),
        ]))
        
        self.encoder_video = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(train_dataset.video_embedding_size, 1600)),
            ('relu1', nn.Sigmoid()),
            ('linr2', nn.Linear(1600, 1000)),
            ('relu2', nn.Sigmoid()),
            ('linr3', nn.Linear(1000, 500)),
            ('relu3', nn.LeakyReLU()),
            ('linr4', nn.Linear(500, 200)),
            ('relu4', nn.LeakyReLU()),
        ]))
        
        self.encoder_audio = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(train_dataset.audio_embedding_size, 256)),
            ('relu1', nn.Sigmoid()),
            ('linr2', nn.Linear(256, 200)),
            ('relu2', nn.LeakyReLU()),
        ]))
        
        self.encoder_text = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(train_dataset.text_embedding_size, 100)),
            ('relu1', nn.LeakyReLU()),
            ('linr2', nn.Linear(100, 200)),
            ('relu2', nn.LeakyReLU()),
        ]))
        
        self.siamese = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(200, 512)),
            ('relu1', nn.LeakyReLU()),
            ('linr2', nn.Linear(512, 256)),
            ('relu2', nn.LeakyReLU()),
            ('linr3', nn.Linear(256, 100)),
            ('relu3', nn.LeakyReLU()),
        ]))
        
        self.ffn = nn.Sequential(OrderedDict([
            ('linr1', nn.Linear(200, 164)),
            ('actv1', nn.LeakyReLU()),
            ('linr2', nn.Linear(164, 50)),
            ('actv2', nn.LeakyReLU()),
            ('linr4', nn.Linear(50, 1)),
        ]))
        
        self.device = device
        self.encoder_user.apply(self.init_weights)
        self.encoder_item.apply(self.init_weights)
        self.encoder_video.apply(self.init_weights)
        self.encoder_audio.apply(self.init_weights)
        self.encoder_text.apply(self.init_weights)
        self.siamese.apply(self.init_weights)
        self.ffn.apply(self.init_weights)
        
    def init_weights(self, m):
        if isinstance(m, nn.Linear):
            nn.init.kaiming_normal_(m.weight)
            m.bias.data.fill_(0.01)
        
    def forward(self, x1, x2):
        outu = self.encoder_user(x1)
        outr = self.encoder_item(x2[3])
        outv = self.encoder_video(x2[0])
        outa = self.encoder_audio(x2[1])
        outt = self.encoder_text(x2[2])
#         outi = torch.cat((outt), axis=1)
        outi = outt
        out1 = self.siamese(outu)
        out2 = self.siamese(outi)
        diff = torch.cat((out1, out2), axis=1)
        out = self.ffn(diff)
        return(out, outu, outi)
    
    def fit(self, trainloader = trainloader, 
            testloader = testloader, epochs = 200):
        self.criterion_rate = nn.MSELoss()
        self.criterion_embd = nn.CosineEmbeddingLoss()
        self.optimizer = optim.Adam(self.parameters(), lr = 5e-4, weight_decay = 1e-4)
        
        train_loss = []
        train_f1 = []
        test_loss = []
        test_f1 = []
        for epoch in range(epochs):
            running_loss = 0.0
            running_loss_1 = 0.0
            
            for i, data in tqdm(enumerate(trainloader)):
                self.train()
                x1, x2, y = data
                y_flt = y.type(torch.FloatTensor).to(device)
                y_lng = torch.div(y, 4, rounding_mode="floor").to(device)
                self.optimizer.zero_grad()
                reg, outu, outi = self.forward(x1, x2)
                loss_1 = self.criterion_rate(reg.squeeze(), y_flt)
                loss_2 = self.criterion_embd(outu, outi, y_lng * 2 - 1)
                loss = loss_1 + loss_2 
                loss.backward()
                self.optimizer.step()

                running_loss_1 += torch.sqrt(loss_1)
                running_loss += loss
            vl, vp, vr, vf, tp, tr, tf = self.evaluate()
            print('Epoch-%d: Loss = %.3f\nTrain RMSE = %.3f||Train Precision = %.3f||Train Recall = %.3f\nTest RMSE = %.3f || Test Precision = %.3f|| Test Recall = %.3f'%
                  (epoch + 1, running_loss / i, running_loss_1 / i, 
                   tp, tr, vl, vp, vr))
            train_loss.append((running_loss_1 / i).cpu().detach().numpy())
            test_loss.append(vl.cpu().detach().numpy())
            train_f1.append(tf)
            test_f1.append(vf)
        return(train_loss, test_loss, train_f1, test_f1)
            
    def evaluate(self, k = 3.35):
        self.eval()
        with torch.no_grad():
            valdata = next(iter(testloader))
            x1, x2, y = valdata
            y_flt = y.type(torch.FloatTensor).to(device)
            y_lng = torch.div(y, 4, rounding_mode="floor").to(device)
            otpt = self.forward(x1, x2)
            print(otpt[0])
            pred = (otpt[0] > k).float()
            vl = torch.sqrt(self.criterion_rate(otpt[0].squeeze(), y_flt))
            vp = precision_score(y_lng.cpu(), pred.cpu())
            vr = recall_score(y_lng.cpu(), pred.cpu())
            vf = f1_score(y_lng.cpu(), pred.cpu())
            print(classification_report(y_lng.cpu(), pred.cpu(),
                    target_names = ["0", "1"]))
            
            traindata = next(iter(trainloader))
            x1, x2, y = traindata
            y_flt = y.type(torch.FloatTensor).to(device)
            y_lng = torch.div(y, 4, rounding_mode="floor").to(device)
            otpt = self.forward(x1, x2)
            pred = (otpt[0] > k).float()
            tp = precision_score(y_lng.cpu(), pred.cpu())
            tr = recall_score(y_lng.cpu(), pred.cpu())
            tf = f1_score(y_lng.cpu(), pred.cpu())
        return(vl, vp*100, vr*100, vf*100, tp*100, tr*100, tf*100)

In [24]:
sm_net = SiameseNet()
sm_net.to(device)

SiameseNet(
  (encoder_user): Sequential(
    (linr1): Linear(in_features=1682, out_features=1024, bias=True)
    (relu1): LeakyReLU(negative_slope=0.01)
    (linr2): Linear(in_features=1024, out_features=200, bias=True)
    (relu2): LeakyReLU(negative_slope=0.01)
  )
  (encoder_item): Sequential(
    (linr1): Linear(in_features=943, out_features=256, bias=True)
    (relu1): Sigmoid()
    (linr2): Linear(in_features=256, out_features=200, bias=True)
    (relu2): LeakyReLU(negative_slope=0.01)
  )
  (encoder_video): Sequential(
    (linr1): Linear(in_features=2048, out_features=1600, bias=True)
    (relu1): Sigmoid()
    (linr2): Linear(in_features=1600, out_features=1000, bias=True)
    (relu2): Sigmoid()
    (linr3): Linear(in_features=1000, out_features=500, bias=True)
    (relu3): LeakyReLU(negative_slope=0.01)
    (linr4): Linear(in_features=500, out_features=200, bias=True)
    (relu4): LeakyReLU(negative_slope=0.01)
  )
  (encoder_audio): Sequential(
    (linr1): Linear(in_featur

In [ ]:
train_loss, test_loss, train_f1, test_f1 = sm_net.fit()

3it [00:25,  8.64s/it]


tensor([[1.6902],
        [1.8574],
        [1.6902],
        ...,
        [2.1537],
        [2.0538],
        [2.0912]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.44      0.94      0.60      8765
           1       0.55      0.06      0.10     11235

    accuracy                           0.44     20000
   macro avg       0.49      0.50      0.35     20000
weighted avg       0.50      0.44      0.32     20000

Epoch-1: Loss = 10.919
Train RMSE = 3.746||Train Precision = 57.072||Train Recall = 14.610
Test RMSE = 1.854 || Test Precision = 55.095|| Test Recall = 5.679


3it [00:21,  7.24s/it]


tensor([[3.1411],
        [3.3875],
        [3.1411],
        ...,
        [3.3955],
        [3.3239],
        [3.2850]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.45      0.50      0.48      8765
           1       0.58      0.53      0.55     11235

    accuracy                           0.52     20000
   macro avg       0.52      0.52      0.51     20000
weighted avg       0.52      0.52      0.52     20000

Epoch-2: Loss = 4.308
Train RMSE = 2.294||Train Precision = 56.706||Train Recall = 67.604
Test RMSE = 1.449 || Test Precision = 57.666|| Test Recall = 53.164


3it [00:21,  7.23s/it]


tensor([[2.7836],
        [3.2609],
        [2.7836],
        ...,
        [3.2724],
        [3.4516],
        [3.7446]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.47      0.74      0.57      8765
           1       0.63      0.35      0.45     11235

    accuracy                           0.52     20000
   macro avg       0.55      0.54      0.51     20000
weighted avg       0.56      0.52      0.50     20000

Epoch-3: Loss = 3.390
Train RMSE = 1.973||Train Precision = 63.161||Train Recall = 41.583
Test RMSE = 1.323 || Test Precision = 63.054|| Test Recall = 34.802


3it [00:21,  7.19s/it]


tensor([[3.5265],
        [4.1390],
        [3.5265],
        ...,
        [3.7262],
        [3.9145],
        [4.5443]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.50      0.38      0.43      8765
           1       0.59      0.71      0.64     11235

    accuracy                           0.56     20000
   macro avg       0.55      0.54      0.54     20000
weighted avg       0.55      0.56      0.55     20000

Epoch-4: Loss = 2.918
Train RMSE = 1.789||Train Precision = 58.587||Train Recall = 79.369
Test RMSE = 1.219 || Test Precision = 59.280|| Test Recall = 70.619


3it [00:21,  7.20s/it]


tensor([[3.1355],
        [3.7288],
        [3.1355],
        ...,
        [2.9721],
        [3.5462],
        [4.4331]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.51      0.65      0.57      8765
           1       0.65      0.51      0.57     11235

    accuracy                           0.57     20000
   macro avg       0.58      0.58      0.57     20000
weighted avg       0.59      0.57      0.57     20000

Epoch-5: Loss = 2.738
Train RMSE = 1.713||Train Precision = 65.086||Train Recall = 55.223
Test RMSE = 1.189 || Test Precision = 64.976|| Test Recall = 50.841


3it [00:21,  7.18s/it]


tensor([[3.5794],
        [4.1809],
        [3.5794],
        ...,
        [3.0449],
        [3.7525],
        [4.7063]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.56      0.41      0.48      8765
           1       0.62      0.74      0.68     11235

    accuracy                           0.60     20000
   macro avg       0.59      0.58      0.58     20000
weighted avg       0.59      0.60      0.59     20000

Epoch-6: Loss = 2.630
Train RMSE = 1.666||Train Precision = 59.997||Train Recall = 80.987
Test RMSE = 1.148 || Test Precision = 61.945|| Test Recall = 74.499


3it [00:21,  7.19s/it]


tensor([[3.1750],
        [3.7223],
        [3.1750],
        ...,
        [2.7325],
        [3.4242],
        [4.3755]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.54      0.62      0.58      8765
           1       0.66      0.58      0.62     11235

    accuracy                           0.60     20000
   macro avg       0.60      0.60      0.60     20000
weighted avg       0.61      0.60      0.60     20000

Epoch-7: Loss = 2.538
Train RMSE = 1.625||Train Precision = 66.803||Train Recall = 60.999
Test RMSE = 1.131 || Test Precision = 66.255|| Test Recall = 57.793


3it [00:21,  7.20s/it]


tensor([[3.4598],
        [3.9980],
        [3.4598],
        ...,
        [2.9445],
        [3.6379],
        [4.4898]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.59      0.42      0.49      8765
           1       0.63      0.78      0.70     11235

    accuracy                           0.62     20000
   macro avg       0.61      0.60      0.59     20000
weighted avg       0.62      0.62      0.61     20000

Epoch-8: Loss = 2.474
Train RMSE = 1.596||Train Precision = 62.333||Train Recall = 81.924
Test RMSE = 1.106 || Test Precision = 63.170|| Test Recall = 77.552


3it [00:21,  7.19s/it]


tensor([[3.2722],
        [3.7265],
        [3.2722],
        ...,
        [2.8295],
        [3.4285],
        [4.2127]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.57      0.57      0.57      8765
           1       0.67      0.67      0.67     11235

    accuracy                           0.63     20000
   macro avg       0.62      0.62      0.62     20000
weighted avg       0.63      0.63      0.63     20000

Epoch-9: Loss = 2.426
Train RMSE = 1.574||Train Precision = 67.475||Train Recall = 68.883
Test RMSE = 1.091 || Test Precision = 66.575|| Test Recall = 66.889


3it [00:21,  7.22s/it]


tensor([[3.4747],
        [3.8954],
        [3.4747],
        ...,
        [3.0052],
        [3.4995],
        [4.2232]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.61      0.46      0.52      8765
           1       0.65      0.77      0.70     11235

    accuracy                           0.63     20000
   macro avg       0.63      0.61      0.61     20000
weighted avg       0.63      0.63      0.62     20000

Epoch-10: Loss = 2.382
Train RMSE = 1.555||Train Precision = 63.736||Train Recall = 80.844
Test RMSE = 1.077 || Test Precision = 64.584|| Test Recall = 77.374


3it [00:21,  7.22s/it]


tensor([[3.4052],
        [3.7581],
        [3.4052],
        ...,
        [3.0080],
        [3.3782],
        [4.0526]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.60      0.55      0.57      8765
           1       0.67      0.72      0.69     11235

    accuracy                           0.64     20000
   macro avg       0.64      0.63      0.63     20000
weighted avg       0.64      0.64      0.64     20000

Epoch-11: Loss = 2.343
Train RMSE = 1.537||Train Precision = 66.834||Train Recall = 74.769
Test RMSE = 1.068 || Test Precision = 67.098|| Test Recall = 71.954


3it [00:21,  7.19s/it]


tensor([[3.5380],
        [3.8579],
        [3.5380],
        ...,
        [3.1617],
        [3.4405],
        [4.0763]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.63      0.50      0.56      8765
           1       0.66      0.77      0.71     11235

    accuracy                           0.65     20000
   macro avg       0.64      0.63      0.63     20000
weighted avg       0.65      0.65      0.64     20000

Epoch-12: Loss = 2.315
Train RMSE = 1.525||Train Precision = 65.755||Train Recall = 79.863
Test RMSE = 1.059 || Test Precision = 66.269|| Test Recall = 76.591


3it [00:21,  7.24s/it]


tensor([[3.5374],
        [3.8305],
        [3.5374],
        ...,
        [3.2181],
        [3.4463],
        [4.0358]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.63      0.53      0.57      8765
           1       0.67      0.76      0.71     11235

    accuracy                           0.66     20000
   macro avg       0.65      0.64      0.64     20000
weighted avg       0.65      0.66      0.65     20000

Epoch-13: Loss = 2.291
Train RMSE = 1.514||Train Precision = 66.761||Train Recall = 77.922
Test RMSE = 1.051 || Test Precision = 67.156|| Test Recall = 75.745


3it [00:21,  7.22s/it]


tensor([[3.6172],
        [3.8995],
        [3.6172],
        ...,
        [3.3159],
        [3.4891],
        [4.0182]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.64      0.51      0.57      8765
           1       0.67      0.78      0.72     11235

    accuracy                           0.66     20000
   macro avg       0.66      0.64      0.64     20000
weighted avg       0.66      0.66      0.65     20000

Epoch-14: Loss = 2.266
Train RMSE = 1.503||Train Precision = 66.200||Train Recall = 80.533
Test RMSE = 1.044 || Test Precision = 67.041|| Test Recall = 78.015


3it [00:21,  7.20s/it]


tensor([[3.6179],
        [3.8948],
        [3.6179],
        ...,
        [3.3469],
        [3.4871],
        [3.9331]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.65      0.52      0.58      8765
           1       0.68      0.78      0.72     11235

    accuracy                           0.67     20000
   macro avg       0.66      0.65      0.65     20000
weighted avg       0.66      0.67      0.66     20000

Epoch-15: Loss = 2.246
Train RMSE = 1.494||Train Precision = 66.912||Train Recall = 79.523
Test RMSE = 1.038 || Test Precision = 67.730|| Test Recall = 77.828


3it [00:21,  7.19s/it]


tensor([[3.6468],
        [3.9313],
        [3.6468],
        ...,
        [3.3998],
        [3.5255],
        [3.8651]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.66      0.51      0.58      8765
           1       0.68      0.79      0.73     11235

    accuracy                           0.67     20000
   macro avg       0.67      0.65      0.65     20000
weighted avg       0.67      0.67      0.66     20000

Epoch-16: Loss = 2.227
Train RMSE = 1.486||Train Precision = 66.919||Train Recall = 81.331
Test RMSE = 1.032 || Test Precision = 67.503|| Test Recall = 79.243


3it [00:21,  7.20s/it]


tensor([[3.5882],
        [3.8804],
        [3.5882],
        ...,
        [3.4050],
        [3.5405],
        [3.7680]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.65      0.56      0.60      8765
           1       0.69      0.77      0.73     11235

    accuracy                           0.68     20000
   macro avg       0.67      0.66      0.66     20000
weighted avg       0.67      0.68      0.67     20000

Epoch-17: Loss = 2.209
Train RMSE = 1.477||Train Precision = 68.552||Train Recall = 78.191
Test RMSE = 1.027 || Test Precision = 68.951|| Test Recall = 76.849


3it [00:21,  7.18s/it]


tensor([[3.6755],
        [3.9974],
        [3.6755],
        ...,
        [3.5069],
        [3.6727],
        [3.7860]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.68      0.50      0.57      8765
           1       0.68      0.81      0.74     11235

    accuracy                           0.68     20000
   macro avg       0.68      0.66      0.66     20000
weighted avg       0.68      0.68      0.67     20000

Epoch-18: Loss = 2.188
Train RMSE = 1.468||Train Precision = 67.319||Train Recall = 83.352
Test RMSE = 1.023 || Test Precision = 67.520|| Test Recall = 81.486


3it [00:21,  7.16s/it]


tensor([[3.5985],
        [3.9110],
        [3.5985],
        ...,
        [3.4781],
        [3.6378],
        [3.6402]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.66      0.57      0.61      8765
           1       0.70      0.77      0.73     11235

    accuracy                           0.68     20000
   macro avg       0.68      0.67      0.67     20000
weighted avg       0.68      0.68      0.68     20000

Epoch-19: Loss = 2.174
Train RMSE = 1.462||Train Precision = 69.378||Train Recall = 77.350
Test RMSE = 1.018 || Test Precision = 69.806|| Test Recall = 76.733


3it [00:21,  7.15s/it]


tensor([[3.6893],
        [4.0148],
        [3.6893],
        ...,
        [3.5481],
        [3.7275],
        [3.6400]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.68      0.54      0.60      8765
           1       0.69      0.80      0.74     11235

    accuracy                           0.68     20000
   macro avg       0.68      0.67      0.67     20000
weighted avg       0.68      0.68      0.68     20000

Epoch-20: Loss = 2.154
Train RMSE = 1.454||Train Precision = 68.290||Train Recall = 81.197
Test RMSE = 1.013 || Test Precision = 68.894|| Test Recall = 80.036


3it [00:21,  7.16s/it]


tensor([[3.6813],
        [3.9966],
        [3.6813],
        ...,
        [3.5507],
        [3.7327],
        [3.5925]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.67      0.56      0.61      8765
           1       0.70      0.79      0.74     11235

    accuracy                           0.69     20000
   macro avg       0.68      0.67      0.68     20000
weighted avg       0.69      0.69      0.68     20000

Epoch-21: Loss = 2.140
Train RMSE = 1.448||Train Precision = 69.368||Train Recall = 79.796
Test RMSE = 1.009 || Test Precision = 69.710|| Test Recall = 78.638


3it [00:21,  7.14s/it]


tensor([[3.6980],
        [4.0066],
        [3.6980],
        ...,
        [3.5880],
        [3.7419],
        [3.5423]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.68      0.56      0.62      8765
           1       0.70      0.79      0.74     11235

    accuracy                           0.69     20000
   macro avg       0.69      0.68      0.68     20000
weighted avg       0.69      0.69      0.69     20000

Epoch-22: Loss = 2.123
Train RMSE = 1.440||Train Precision = 69.829||Train Recall = 80.472
Test RMSE = 1.005 || Test Precision = 69.888|| Test Recall = 78.852


3it [00:21,  7.15s/it]


tensor([[3.7654],
        [4.0600],
        [3.7654],
        ...,
        [3.6385],
        [3.7746],
        [3.5284]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.68      0.55      0.61      8765
           1       0.70      0.80      0.75     11235

    accuracy                           0.69     20000
   macro avg       0.69      0.68      0.68     20000
weighted avg       0.69      0.69      0.69     20000

Epoch-23: Loss = 2.109
Train RMSE = 1.435||Train Precision = 69.344||Train Recall = 82.149
Test RMSE = 1.001 || Test Precision = 69.677|| Test Recall = 80.134


3it [00:21,  7.13s/it]


tensor([[3.7861],
        [4.0658],
        [3.7861],
        ...,
        [3.6657],
        [3.7648],
        [3.4961]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.56      0.62      8765
           1       0.70      0.80      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.69      0.68      0.68     20000
weighted avg       0.69      0.70      0.69     20000

Epoch-24: Loss = 2.096
Train RMSE = 1.429||Train Precision = 70.000||Train Recall = 81.014
Test RMSE = 0.998 || Test Precision = 70.072|| Test Recall = 80.027


3it [00:21,  7.14s/it]


tensor([[3.8131],
        [4.0779],
        [3.8131],
        ...,
        [3.6880],
        [3.7656],
        [3.4872]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.56      0.62      8765
           1       0.70      0.80      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.68      0.68     20000
weighted avg       0.70      0.70      0.69     20000

Epoch-25: Loss = 2.083
Train RMSE = 1.424||Train Precision = 69.777||Train Recall = 81.490
Test RMSE = 0.995 || Test Precision = 70.034|| Test Recall = 80.463


3it [00:21,  7.15s/it]


tensor([[3.8433],
        [4.0938],
        [3.8433],
        ...,
        [3.7101],
        [3.7608],
        [3.4841]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.56      0.62      8765
           1       0.70      0.81      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.68      0.68     20000
weighted avg       0.70      0.70      0.69     20000

Epoch-26: Loss = 2.075
Train RMSE = 1.421||Train Precision = 69.677||Train Recall = 81.210
Test RMSE = 0.993 || Test Precision = 70.121|| Test Recall = 80.774


3it [00:21,  7.12s/it]


tensor([[3.8480],
        [4.0863],
        [3.8480],
        ...,
        [3.7325],
        [3.7549],
        [3.4996]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.56      0.62      8765
           1       0.70      0.81      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.70      0.70     20000

Epoch-27: Loss = 2.065
Train RMSE = 1.417||Train Precision = 69.816||Train Recall = 81.514
Test RMSE = 0.991 || Test Precision = 70.319|| Test Recall = 80.765


3it [00:21,  7.13s/it]


tensor([[3.8347],
        [4.0415],
        [3.8347],
        ...,
        [3.7257],
        [3.7049],
        [3.4733]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.59      0.63      8765
           1       0.71      0.79      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.70      0.70     20000

Epoch-28: Loss = 2.055
Train RMSE = 1.414||Train Precision = 70.578||Train Recall = 79.685
Test RMSE = 0.989 || Test Precision = 71.168|| Test Recall = 79.315


3it [00:21,  7.12s/it]


tensor([[3.8250],
        [4.0166],
        [3.8250],
        ...,
        [3.7497],
        [3.7025],
        [3.4967]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.58      0.63      8765
           1       0.71      0.80      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.70      0.70     20000

Epoch-29: Loss = 2.047
Train RMSE = 1.412||Train Precision = 70.632||Train Recall = 80.720
Test RMSE = 0.987 || Test Precision = 70.947|| Test Recall = 80.205


3it [00:21,  7.12s/it]


tensor([[3.8508],
        [4.0490],
        [3.8508],
        ...,
        [3.7823],
        [3.7399],
        [3.5713]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.55      0.62      8765
           1       0.70      0.82      0.76     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.70      0.70     20000

Epoch-30: Loss = 2.038
Train RMSE = 1.408||Train Precision = 69.175||Train Recall = 82.967
Test RMSE = 0.986 || Test Precision = 70.080|| Test Recall = 82.305


3it [00:21,  7.14s/it]


tensor([[3.8664],
        [4.0460],
        [3.8664],
        ...,
        [3.7743],
        [3.7167],
        [3.5705]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.55      0.62      8765
           1       0.70      0.82      0.76     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.70      0.70     20000

Epoch-31: Loss = 2.030
Train RMSE = 1.406||Train Precision = 69.638||Train Recall = 82.635
Test RMSE = 0.984 || Test Precision = 70.245|| Test Recall = 82.012


3it [00:21,  7.11s/it]


tensor([[3.8370],
        [4.0000],
        [3.8370],
        ...,
        [3.7672],
        [3.6811],
        [3.5197]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.57      0.63      8765
           1       0.71      0.81      0.75     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.70      0.70     20000

Epoch-32: Loss = 2.025
Train RMSE = 1.405||Train Precision = 70.642||Train Recall = 81.334
Test RMSE = 0.983 || Test Precision = 70.675|| Test Recall = 80.979


3it [00:21,  7.14s/it]


tensor([[3.8527],
        [4.0068],
        [3.8527],
        ...,
        [3.7576],
        [3.7069],
        [3.5114]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.57      0.63      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-33: Loss = 2.017
Train RMSE = 1.402||Train Precision = 70.544||Train Recall = 81.437
Test RMSE = 0.982 || Test Precision = 70.711|| Test Recall = 81.397


3it [00:21,  7.14s/it]


tensor([[3.8526],
        [3.9953],
        [3.8526],
        ...,
        [3.7459],
        [3.7060],
        [3.4824]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.57      0.63      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-34: Loss = 2.014
Train RMSE = 1.402||Train Precision = 70.332||Train Recall = 81.935
Test RMSE = 0.981 || Test Precision = 70.636|| Test Recall = 81.362


3it [00:21,  7.12s/it]


tensor([[3.8337],
        [3.9528],
        [3.8337],
        ...,
        [3.7540],
        [3.6912],
        [3.4543]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.57      0.63      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.70      0.69      0.69     20000
weighted avg       0.70      0.71      0.70     20000

Epoch-35: Loss = 2.006
Train RMSE = 1.399||Train Precision = 70.018||Train Recall = 81.570
Test RMSE = 0.980 || Test Precision = 70.694|| Test Recall = 81.202


3it [00:21,  7.12s/it]


tensor([[3.8431],
        [3.9721],
        [3.8431],
        ...,
        [3.7600],
        [3.7126],
        [3.5063]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.56      0.63      8765
           1       0.70      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-36: Loss = 2.000
Train RMSE = 1.397||Train Precision = 70.372||Train Recall = 82.635
Test RMSE = 0.979 || Test Precision = 70.491|| Test Recall = 82.092


3it [00:21,  7.12s/it]


tensor([[3.9007],
        [4.0608],
        [3.9007],
        ...,
        [3.7921],
        [3.7478],
        [3.5164]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.53      0.61      8765
           1       0.70      0.84      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-37: Loss = 1.996
Train RMSE = 1.397||Train Precision = 68.765||Train Recall = 84.270
Test RMSE = 0.979 || Test Precision = 69.725|| Test Recall = 84.068


3it [00:21,  7.13s/it]


tensor([[3.8841],
        [4.0375],
        [3.8841],
        ...,
        [3.7933],
        [3.6899],
        [3.4547]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.55      0.62      8765
           1       0.70      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-38: Loss = 1.992
Train RMSE = 1.396||Train Precision = 69.579||Train Recall = 82.707
Test RMSE = 0.978 || Test Precision = 70.275|| Test Recall = 82.572


3it [00:21,  7.15s/it]


tensor([[3.9166],
        [4.0799],
        [3.9166],
        ...,
        [3.7968],
        [3.7075],
        [3.5162]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.54      0.62      8765
           1       0.70      0.84      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-39: Loss = 1.988
Train RMSE = 1.396||Train Precision = 69.810||Train Recall = 84.004
Test RMSE = 0.978 || Test Precision = 70.019|| Test Recall = 83.587


3it [00:21,  7.12s/it]


tensor([[3.8828],
        [4.0304],
        [3.8828],
        ...,
        [3.8029],
        [3.6727],
        [3.4841]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.55      0.62      8765
           1       0.70      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-40: Loss = 1.983
Train RMSE = 1.395||Train Precision = 69.729||Train Recall = 83.547
Test RMSE = 0.976 || Test Precision = 70.168|| Test Recall = 83.008


3it [00:21,  7.14s/it]


tensor([[3.8441],
        [3.9845],
        [3.8441],
        ...,
        [3.7674],
        [3.6473],
        [3.4674]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.56      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-41: Loss = 1.981
Train RMSE = 1.395||Train Precision = 70.236||Train Recall = 82.055
Test RMSE = 0.976 || Test Precision = 70.636|| Test Recall = 81.896


3it [00:21,  7.12s/it]


tensor([[3.8008],
        [3.9261],
        [3.8008],
        ...,
        [3.7403],
        [3.6235],
        [3.4216]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.60      0.64      8765
           1       0.72      0.79      0.75     11235

    accuracy                           0.71     20000
   macro avg       0.70      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-42: Loss = 1.972
Train RMSE = 1.391||Train Precision = 71.670||Train Recall = 79.303
Test RMSE = 0.977 || Test Precision = 71.565|| Test Recall = 79.413


3it [00:21,  7.16s/it]


tensor([[3.7942],
        [3.8975],
        [3.7942],
        ...,
        [3.7442],
        [3.5931],
        [3.3600]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.61      0.65      8765
           1       0.72      0.79      0.75     11235

    accuracy                           0.71     20000
   macro avg       0.70      0.70      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-43: Loss = 1.971
Train RMSE = 1.392||Train Precision = 71.595||Train Recall = 78.508
Test RMSE = 0.978 || Test Precision = 71.916|| Test Recall = 78.656


3it [00:21,  7.13s/it]


tensor([[3.8380],
        [3.9560],
        [3.8380],
        ...,
        [3.7484],
        [3.6379],
        [3.3768]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.59      0.64      8765
           1       0.71      0.80      0.75     11235

    accuracy                           0.71     20000
   macro avg       0.70      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-44: Loss = 1.969
Train RMSE = 1.392||Train Precision = 71.311||Train Recall = 80.116
Test RMSE = 0.975 || Test Precision = 71.294|| Test Recall = 80.045


3it [00:21,  7.14s/it]


tensor([[3.8504],
        [3.9693],
        [3.8504],
        ...,
        [3.7481],
        [3.6467],
        [3.3519]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.58      0.64      8765
           1       0.71      0.80      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-45: Loss = 1.959
Train RMSE = 1.388||Train Precision = 71.283||Train Recall = 80.822
Test RMSE = 0.975 || Test Precision = 71.179|| Test Recall = 80.409


3it [00:21,  7.13s/it]


tensor([[3.8537],
        [3.9702],
        [3.8537],
        ...,
        [3.7815],
        [3.6637],
        [3.4009]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-46: Loss = 1.955
Train RMSE = 1.387||Train Precision = 70.693||Train Recall = 81.656
Test RMSE = 0.974 || Test Precision = 70.840|| Test Recall = 81.584


3it [00:21,  7.13s/it]


tensor([[3.8547],
        [3.9773],
        [3.8547],
        ...,
        [3.7906],
        [3.6544],
        [3.4054]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-47: Loss = 1.954
Train RMSE = 1.388||Train Precision = 71.042||Train Recall = 81.328
Test RMSE = 0.974 || Test Precision = 70.880|| Test Recall = 81.611


3it [00:21,  7.14s/it]


tensor([[3.8599],
        [3.9874],
        [3.8599],
        ...,
        [3.7548],
        [3.6264],
        [3.3495]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.58      0.64      8765
           1       0.71      0.80      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-48: Loss = 1.951
Train RMSE = 1.388||Train Precision = 71.838||Train Recall = 80.437
Test RMSE = 0.974 || Test Precision = 71.246|| Test Recall = 80.409


3it [00:21,  7.16s/it]


tensor([[3.8485],
        [3.9957],
        [3.8485],
        ...,
        [3.7624],
        [3.6529],
        [3.3693]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.58      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-49: Loss = 1.948
Train RMSE = 1.388||Train Precision = 71.160||Train Recall = 80.599
Test RMSE = 0.973 || Test Precision = 71.142|| Test Recall = 80.837


3it [00:21,  7.13s/it]


tensor([[3.8363],
        [3.9777],
        [3.8363],
        ...,
        [3.7619],
        [3.6450],
        [3.3791]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.58      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-50: Loss = 1.942
Train RMSE = 1.385||Train Precision = 70.708||Train Recall = 80.758
Test RMSE = 0.973 || Test Precision = 71.190|| Test Recall = 80.917


3it [00:21,  7.16s/it]


tensor([[3.8543],
        [3.9931],
        [3.8543],
        ...,
        [3.7767],
        [3.6609],
        [3.4245]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.58      0.63      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-51: Loss = 1.937
Train RMSE = 1.384||Train Precision = 71.418||Train Recall = 81.650
Test RMSE = 0.973 || Test Precision = 71.034|| Test Recall = 81.264


3it [00:21,  7.13s/it]


tensor([[3.8480],
        [3.9794],
        [3.8480],
        ...,
        [3.7466],
        [3.6449],
        [3.4149]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.57      0.63      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-52: Loss = 1.932
Train RMSE = 1.383||Train Precision = 71.338||Train Recall = 81.203
Test RMSE = 0.973 || Test Precision = 70.915|| Test Recall = 81.228


3it [00:21,  7.17s/it]


tensor([[3.8543],
        [3.9761],
        [3.8543],
        ...,
        [3.7546],
        [3.6677],
        [3.4167]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.56      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-53: Loss = 1.930
Train RMSE = 1.383||Train Precision = 70.736||Train Recall = 82.528
Test RMSE = 0.972 || Test Precision = 70.629|| Test Recall = 82.127


3it [00:21,  7.12s/it]


tensor([[3.8777],
        [4.0057],
        [3.8777],
        ...,
        [3.7672],
        [3.6808],
        [3.4666]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-54: Loss = 1.927
Train RMSE = 1.382||Train Precision = 70.405||Train Recall = 82.240
Test RMSE = 0.972 || Test Precision = 70.523|| Test Recall = 82.519


3it [00:21,  7.11s/it]


tensor([[3.8843],
        [3.9945],
        [3.8843],
        ...,
        [3.7745],
        [3.6761],
        [3.4358]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.56      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-55: Loss = 1.925
Train RMSE = 1.382||Train Precision = 70.938||Train Recall = 81.910
Test RMSE = 0.972 || Test Precision = 70.681|| Test Recall = 82.074


3it [00:21,  7.13s/it]


tensor([[3.9023],
        [4.0205],
        [3.9023],
        ...,
        [3.7985],
        [3.7084],
        [3.4476]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-56: Loss = 1.922
Train RMSE = 1.382||Train Precision = 70.665||Train Recall = 82.490
Test RMSE = 0.971 || Test Precision = 70.622|| Test Recall = 82.741


3it [00:21,  7.12s/it]


tensor([[3.9799],
        [4.1495],
        [3.9799],
        ...,
        [3.8571],
        [3.7731],
        [3.5303]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.50      0.60      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.70     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.71      0.70      0.69     20000

Epoch-57: Loss = 1.922
Train RMSE = 1.383||Train Precision = 68.130||Train Recall = 87.282
Test RMSE = 0.975 || Test Precision = 68.829|| Test Recall = 86.595


3it [00:21,  7.12s/it]


tensor([[3.9683],
        [4.1342],
        [3.9683],
        ...,
        [3.8276],
        [3.7558],
        [3.5099]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.51      0.60      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-58: Loss = 1.918
Train RMSE = 1.382||Train Precision = 69.504||Train Recall = 86.056
Test RMSE = 0.974 || Test Precision = 69.244|| Test Recall = 85.928


3it [00:21,  7.12s/it]


tensor([[3.9345],
        [4.0862],
        [3.9345],
        ...,
        [3.8091],
        [3.7385],
        [3.4908]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-59: Loss = 1.915
Train RMSE = 1.382||Train Precision = 70.103||Train Recall = 84.345
Test RMSE = 0.971 || Test Precision = 70.048|| Test Recall = 84.263


3it [00:21,  7.10s/it]


tensor([[3.9014],
        [4.0412],
        [3.9014],
        ...,
        [3.7991],
        [3.7345],
        [3.4822]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.55      0.62      8765
           1       0.70      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-60: Loss = 1.910
Train RMSE = 1.380||Train Precision = 70.071||Train Recall = 83.284
Test RMSE = 0.970 || Test Precision = 70.395|| Test Recall = 83.240


3it [00:21,  7.13s/it]


tensor([[3.8907],
        [4.0294],
        [3.8907],
        ...,
        [3.7602],
        [3.7001],
        [3.4284]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.56      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-61: Loss = 1.908
Train RMSE = 1.380||Train Precision = 70.953||Train Recall = 82.227
Test RMSE = 0.970 || Test Precision = 70.679|| Test Recall = 82.261


3it [00:21,  7.09s/it]


tensor([[3.8482],
        [3.9732],
        [3.8482],
        ...,
        [3.6994],
        [3.6461],
        [3.3505]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.60      0.65      8765
           1       0.72      0.80      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-62: Loss = 1.912
Train RMSE = 1.383||Train Precision = 71.796||Train Recall = 79.115
Test RMSE = 0.972 || Test Precision = 71.853|| Test Recall = 79.911


3it [00:21,  7.12s/it]


tensor([[3.8123],
        [3.9149],
        [3.8123],
        ...,
        [3.7113],
        [3.6362],
        [3.3207]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.61      0.65      8765
           1       0.72      0.79      0.75     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-63: Loss = 1.904
Train RMSE = 1.379||Train Precision = 72.561||Train Recall = 78.050
Test RMSE = 0.973 || Test Precision = 72.084|| Test Recall = 79.039


3it [00:21,  7.12s/it]


tensor([[3.8594],
        [3.9714],
        [3.8594],
        ...,
        [3.7266],
        [3.6751],
        [3.3673]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.59      0.64      8765
           1       0.72      0.80      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-64: Loss = 1.902
Train RMSE = 1.380||Train Precision = 72.013||Train Recall = 79.554
Test RMSE = 0.971 || Test Precision = 71.584|| Test Recall = 80.160


3it [00:21,  7.12s/it]


tensor([[3.9043],
        [4.0409],
        [3.9043],
        ...,
        [3.7295],
        [3.7111],
        [3.4055]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-65: Loss = 1.896
Train RMSE = 1.378||Train Precision = 71.596||Train Recall = 81.794
Test RMSE = 0.970 || Test Precision = 71.016|| Test Recall = 81.673


3it [00:21,  7.15s/it]


tensor([[3.8983],
        [4.0020],
        [3.8983],
        ...,
        [3.7569],
        [3.6857],
        [3.3897]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.58      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-66: Loss = 1.892
Train RMSE = 1.376||Train Precision = 71.177||Train Recall = 80.836
Test RMSE = 0.970 || Test Precision = 71.193|| Test Recall = 81.193


3it [00:21,  7.13s/it]


tensor([[3.9374],
        [4.0521],
        [3.9374],
        ...,
        [3.7855],
        [3.7221],
        [3.4368]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.55      0.62      8765
           1       0.70      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-67: Loss = 1.894
Train RMSE = 1.379||Train Precision = 70.438||Train Recall = 83.333
Test RMSE = 0.969 || Test Precision = 70.381|| Test Recall = 83.418


3it [00:21,  7.15s/it]


tensor([[3.9782],
        [4.1176],
        [3.9782],
        ...,
        [3.8003],
        [3.7418],
        [3.5276]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-68: Loss = 1.883
Train RMSE = 1.374||Train Precision = 68.844||Train Recall = 85.754
Test RMSE = 0.970 || Test Precision = 69.498|| Test Recall = 85.643


3it [00:21,  7.12s/it]


tensor([[4.0365],
        [4.1843],
        [4.0365],
        ...,
        [3.8175],
        [3.7751],
        [3.5824]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.49      0.59      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.71      0.71      0.69     20000

Epoch-69: Loss = 1.883
Train RMSE = 1.374||Train Precision = 68.475||Train Recall = 87.565
Test RMSE = 0.974 || Test Precision = 68.750|| Test Recall = 87.156


3it [00:21,  7.26s/it]


tensor([[3.9747],
        [4.1024],
        [3.9747],
        ...,
        [3.7881],
        [3.7142],
        [3.5068]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.52      0.61      8765
           1       0.70      0.85      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-70: Loss = 1.891
Train RMSE = 1.380||Train Precision = 69.441||Train Recall = 85.495
Test RMSE = 0.970 || Test Precision = 69.663|| Test Recall = 85.127


3it [00:21,  7.31s/it]


tensor([[3.8632],
        [3.9808],
        [3.8632],
        ...,
        [3.7121],
        [3.6515],
        [3.4640]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.58      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-71: Loss = 1.904
Train RMSE = 1.387||Train Precision = 71.596||Train Recall = 80.830
Test RMSE = 0.969 || Test Precision = 71.306|| Test Recall = 81.219


3it [00:21,  7.11s/it]


tensor([[3.8475],
        [3.9616],
        [3.8475],
        ...,
        [3.7301],
        [3.6364],
        [3.4920]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.58      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-72: Loss = 1.885
Train RMSE = 1.378||Train Precision = 71.468||Train Recall = 81.253
Test RMSE = 0.969 || Test Precision = 71.201|| Test Recall = 81.486


3it [00:21,  7.12s/it]


tensor([[3.8253],
        [3.9442],
        [3.8253],
        ...,
        [3.7188],
        [3.6268],
        [3.4124]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.60      0.65      8765
           1       0.72      0.80      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-73: Loss = 1.880
Train RMSE = 1.376||Train Precision = 72.171||Train Recall = 79.197
Test RMSE = 0.971 || Test Precision = 72.014|| Test Recall = 79.706


3it [00:21,  7.12s/it]


tensor([[3.8742],
        [4.0011],
        [3.8742],
        ...,
        [3.7373],
        [3.6721],
        [3.3833]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.59      0.64      8765
           1       0.72      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-74: Loss = 1.874
Train RMSE = 1.374||Train Precision = 71.856||Train Recall = 80.049
Test RMSE = 0.970 || Test Precision = 71.597|| Test Recall = 80.570


3it [00:21,  7.13s/it]


tensor([[3.9248],
        [4.0367],
        [3.9248],
        ...,
        [3.7461],
        [3.7093],
        [3.4019]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-75: Loss = 1.872
Train RMSE = 1.373||Train Precision = 71.006||Train Recall = 81.779
Test RMSE = 0.968 || Test Precision = 71.030|| Test Recall = 82.163


3it [00:21,  7.13s/it]


tensor([[4.0144],
        [4.1564],
        [4.0144],
        ...,
        [3.8187],
        [3.7813],
        [3.4722]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-76: Loss = 1.871
Train RMSE = 1.374||Train Precision = 69.389||Train Recall = 85.969
Test RMSE = 0.969 || Test Precision = 69.378|| Test Recall = 85.705


3it [00:21,  7.13s/it]


tensor([[3.9822],
        [4.1323],
        [3.9822],
        ...,
        [3.8076],
        [3.7694],
        [3.4897]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-77: Loss = 1.867
Train RMSE = 1.372||Train Precision = 69.734||Train Recall = 85.779
Test RMSE = 0.969 || Test Precision = 69.395|| Test Recall = 85.572


3it [00:21,  7.11s/it]


tensor([[3.9678],
        [4.0870],
        [3.9678],
        ...,
        [3.7988],
        [3.7660],
        [3.4856]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.53      0.61      8765
           1       0.70      0.85      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-78: Loss = 1.858
Train RMSE = 1.369||Train Precision = 69.624||Train Recall = 84.726
Test RMSE = 0.968 || Test Precision = 69.780|| Test Recall = 84.984


3it [00:21,  7.15s/it]


tensor([[4.0190],
        [4.1353],
        [4.0190],
        ...,
        [3.8147],
        [3.7592],
        [3.4230]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.51      0.60      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-79: Loss = 1.857
Train RMSE = 1.369||Train Precision = 69.128||Train Recall = 86.325
Test RMSE = 0.970 || Test Precision = 69.225|| Test Recall = 86.070


3it [00:21,  7.11s/it]


tensor([[4.0716],
        [4.1670],
        [4.0716],
        ...,
        [3.8150],
        [3.8071],
        [3.4960]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.50      0.60      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.71      0.71      0.69     20000

Epoch-80: Loss = 1.858
Train RMSE = 1.370||Train Precision = 68.946||Train Recall = 86.449
Test RMSE = 0.970 || Test Precision = 68.992|| Test Recall = 86.720


3it [00:21,  7.13s/it]


tensor([[4.0170],
        [4.0814],
        [4.0170],
        ...,
        [3.7586],
        [3.7165],
        [3.4108]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-81: Loss = 1.857
Train RMSE = 1.370||Train Precision = 70.115||Train Recall = 84.669
Test RMSE = 0.967 || Test Precision = 70.174|| Test Recall = 84.228


3it [00:21,  7.11s/it]


tensor([[4.0044],
        [4.0853],
        [4.0044],
        ...,
        [3.7442],
        [3.7283],
        [3.4464]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.84      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-82: Loss = 1.849
Train RMSE = 1.366||Train Precision = 70.228||Train Recall = 83.810
Test RMSE = 0.966 || Test Precision = 70.256|| Test Recall = 83.925


3it [00:21,  7.11s/it]


tensor([[3.9530],
        [3.9988],
        [3.9530],
        ...,
        [3.7533],
        [3.6859],
        [3.4248]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-83: Loss = 1.848
Train RMSE = 1.366||Train Precision = 71.098||Train Recall = 83.330
Test RMSE = 0.966 || Test Precision = 70.595|| Test Recall = 83.124


3it [00:21,  7.12s/it]


tensor([[4.0112],
        [4.0894],
        [4.0112],
        ...,
        [3.7992],
        [3.7502],
        [3.4799]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-84: Loss = 1.846
Train RMSE = 1.366||Train Precision = 69.383||Train Recall = 85.977
Test RMSE = 0.967 || Test Precision = 69.486|| Test Recall = 85.616


3it [00:21,  7.11s/it]


tensor([[3.9122],
        [3.9649],
        [3.9122],
        ...,
        [3.7038],
        [3.6681],
        [3.3727]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-85: Loss = 1.843
Train RMSE = 1.365||Train Precision = 71.567||Train Recall = 81.767
Test RMSE = 0.966 || Test Precision = 71.085|| Test Recall = 82.056


3it [00:21,  7.11s/it]


tensor([[3.9714],
        [4.0008],
        [3.9714],
        ...,
        [3.7308],
        [3.6617],
        [3.3985]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-86: Loss = 1.842
Train RMSE = 1.365||Train Precision = 71.396||Train Recall = 83.376
Test RMSE = 0.965 || Test Precision = 70.739|| Test Recall = 83.382


3it [00:21,  7.13s/it]


tensor([[4.0107],
        [4.0737],
        [4.0107],
        ...,
        [3.7248],
        [3.6948],
        [3.3922]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-87: Loss = 1.835
Train RMSE = 1.362||Train Precision = 71.159||Train Recall = 83.267
Test RMSE = 0.965 || Test Precision = 70.766|| Test Recall = 83.275


3it [00:21,  7.10s/it]


tensor([[4.0320],
        [4.0923],
        [4.0320],
        ...,
        [3.7206],
        [3.6974],
        [3.3613]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-88: Loss = 1.834
Train RMSE = 1.363||Train Precision = 70.743||Train Recall = 82.827
Test RMSE = 0.965 || Test Precision = 70.784|| Test Recall = 83.195


3it [00:21,  7.13s/it]


tensor([[4.0035],
        [4.0485],
        [4.0035],
        ...,
        [3.7382],
        [3.7061],
        [3.4336]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-89: Loss = 1.830
Train RMSE = 1.361||Train Precision = 71.313||Train Recall = 83.363
Test RMSE = 0.964 || Test Precision = 70.628|| Test Recall = 83.258


3it [00:21,  7.10s/it]


tensor([[4.0524],
        [4.1234],
        [4.0524],
        ...,
        [3.7414],
        [3.7341],
        [3.4435]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-90: Loss = 1.829
Train RMSE = 1.361||Train Precision = 70.264||Train Recall = 84.192
Test RMSE = 0.964 || Test Precision = 70.092|| Test Recall = 84.441


3it [00:21,  7.12s/it]


tensor([[4.0334],
        [4.0782],
        [4.0334],
        ...,
        [3.7037],
        [3.6845],
        [3.4261]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-91: Loss = 1.828
Train RMSE = 1.361||Train Precision = 71.206||Train Recall = 81.830
Test RMSE = 0.965 || Test Precision = 71.019|| Test Recall = 82.492


3it [00:21,  7.12s/it]


tensor([[3.9828],
        [4.0409],
        [3.9828],
        ...,
        [3.6616],
        [3.6672],
        [3.3763]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.59      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-92: Loss = 1.825
Train RMSE = 1.360||Train Precision = 72.333||Train Recall = 81.030
Test RMSE = 0.965 || Test Precision = 71.490|| Test Recall = 81.175


3it [00:21,  7.13s/it]


tensor([[4.1008],
        [4.2024],
        [4.1008],
        ...,
        [3.7261],
        [3.8039],
        [3.6316]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.49      0.59      8765
           1       0.69      0.88      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.72      0.71      0.69     20000

Epoch-93: Loss = 1.831
Train RMSE = 1.364||Train Precision = 68.771||Train Recall = 87.834
Test RMSE = 0.969 || Test Precision = 68.762|| Test Recall = 87.539


3it [00:21,  7.14s/it]


tensor([[3.9661],
        [4.0306],
        [3.9661],
        ...,
        [3.6003],
        [3.6750],
        [3.4608]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.57      0.63      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-94: Loss = 1.827
Train RMSE = 1.362||Train Precision = 71.593||Train Recall = 81.865
Test RMSE = 0.964 || Test Precision = 71.057|| Test Recall = 82.163


3it [00:21,  7.11s/it]


tensor([[4.0272],
        [4.1086],
        [4.0272],
        ...,
        [3.6304],
        [3.7405],
        [3.4789]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-95: Loss = 1.817
Train RMSE = 1.357||Train Precision = 70.318||Train Recall = 84.311
Test RMSE = 0.964 || Test Precision = 70.183|| Test Recall = 84.326


3it [00:21,  7.13s/it]


tensor([[4.0521],
        [4.1217],
        [4.0521],
        ...,
        [3.6743],
        [3.7521],
        [3.4942]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.51      0.61      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-96: Loss = 1.815
Train RMSE = 1.357||Train Precision = 69.257||Train Recall = 86.476
Test RMSE = 0.965 || Test Precision = 69.354|| Test Recall = 86.213


3it [00:21,  7.22s/it]


tensor([[4.0228],
        [4.0651],
        [4.0228],
        ...,
        [3.6109],
        [3.7077],
        [3.4076]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-97: Loss = 1.815
Train RMSE = 1.357||Train Precision = 71.198||Train Recall = 83.136
Test RMSE = 0.963 || Test Precision = 70.654|| Test Recall = 83.231


3it [00:21,  7.17s/it]


tensor([[4.0214],
        [4.0589],
        [4.0214],
        ...,
        [3.6328],
        [3.6784],
        [3.4157]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.55      0.63      8765
           1       0.71      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-98: Loss = 1.809
Train RMSE = 1.355||Train Precision = 70.905||Train Recall = 83.039
Test RMSE = 0.963 || Test Precision = 70.618|| Test Recall = 83.516


3it [00:21,  7.15s/it]


tensor([[4.0854],
        [4.1319],
        [4.0854],
        ...,
        [3.7063],
        [3.7451],
        [3.5293]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.51      0.61      8765
           1       0.69      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-99: Loss = 1.806
Train RMSE = 1.354||Train Precision = 69.725||Train Recall = 86.737
Test RMSE = 0.965 || Test Precision = 69.425|| Test Recall = 86.257


3it [00:21,  7.27s/it]


tensor([[4.0433],
        [4.0564],
        [4.0433],
        ...,
        [3.6219],
        [3.6692],
        [3.4514]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.57      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-100: Loss = 1.810
Train RMSE = 1.356||Train Precision = 71.792||Train Recall = 82.648
Test RMSE = 0.963 || Test Precision = 71.065|| Test Recall = 82.501


3it [00:21,  7.17s/it]


tensor([[4.0493],
        [4.0647],
        [4.0493],
        ...,
        [3.5945],
        [3.6528],
        [3.4468]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.57      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-101: Loss = 1.803
Train RMSE = 1.353||Train Precision = 71.896||Train Recall = 82.247
Test RMSE = 0.963 || Test Precision = 71.052|| Test Recall = 82.537


3it [00:22,  7.37s/it]


tensor([[4.1073],
        [4.2224],
        [4.1073],
        ...,
        [3.7161],
        [3.8047],
        [3.5603]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.76      0.48      0.59      8765
           1       0.68      0.88      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.72      0.71      0.69     20000

Epoch-102: Loss = 1.803
Train RMSE = 1.353||Train Precision = 68.660||Train Recall = 89.192
Test RMSE = 0.969 || Test Precision = 68.491|| Test Recall = 88.091


3it [00:21,  7.16s/it]


tensor([[3.7885],
        [3.8100],
        [3.7885],
        ...,
        [3.4433],
        [3.4787],
        [3.1242]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.65      0.70      0.67      8765
           1       0.75      0.71      0.73     11235

    accuracy                           0.70     20000
   macro avg       0.70      0.70      0.70     20000
weighted avg       0.71      0.70      0.70     20000

Epoch-103: Loss = 1.842
Train RMSE = 1.375||Train Precision = 76.416||Train Recall = 68.720
Test RMSE = 0.994 || Test Precision = 74.943|| Test Recall = 70.521


3it [00:21,  7.27s/it]


tensor([[3.8978],
        [4.0396],
        [3.8978],
        ...,
        [3.4977],
        [3.6243],
        [3.4258]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.70      0.61      0.65      8765
           1       0.72      0.79      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-104: Loss = 1.863
Train RMSE = 1.387||Train Precision = 72.859||Train Recall = 78.154
Test RMSE = 0.967 || Test Precision = 72.247|| Test Recall = 79.404


3it [00:22,  7.41s/it]


tensor([[4.0144],
        [4.1146],
        [4.0144],
        ...,
        [3.6371],
        [3.7323],
        [3.4489]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.55      0.63      8765
           1       0.71      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.70      0.70     20000
weighted avg       0.72      0.71      0.71     20000

Epoch-105: Loss = 1.826
Train RMSE = 1.367||Train Precision = 70.598||Train Recall = 84.486
Test RMSE = 0.963 || Test Precision = 70.554|| Test Recall = 84.005


3it [00:21,  7.15s/it]


tensor([[4.0796],
        [4.1753],
        [4.0796],
        ...,
        [3.6811],
        [3.7545],
        [3.6208]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.51      0.61      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-106: Loss = 1.809
Train RMSE = 1.358||Train Precision = 69.088||Train Recall = 87.188
Test RMSE = 0.964 || Test Precision = 69.420|| Test Recall = 86.765


3it [00:22,  7.35s/it]


tensor([[4.1603],
        [4.2496],
        [4.1603],
        ...,
        [3.6461],
        [3.7917],
        [3.5933]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.51      0.61      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-107: Loss = 1.803
Train RMSE = 1.355||Train Precision = 69.441||Train Recall = 86.804
Test RMSE = 0.965 || Test Precision = 69.328|| Test Recall = 86.729


3it [00:21,  7.13s/it]


tensor([[4.1136],
        [4.1741],
        [4.1136],
        ...,
        [3.6474],
        [3.7563],
        [3.5482]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.50      0.60      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-108: Loss = 1.795
Train RMSE = 1.351||Train Precision = 69.248||Train Recall = 87.455
Test RMSE = 0.965 || Test Precision = 69.166|| Test Recall = 86.791


3it [00:21,  7.19s/it]


tensor([[4.0954],
        [4.1960],
        [4.0954],
        ...,
        [3.6221],
        [3.7954],
        [3.6183]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.50      0.60      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.72      0.71      0.69     20000

Epoch-109: Loss = 1.794
Train RMSE = 1.351||Train Precision = 69.297||Train Recall = 87.936
Test RMSE = 0.966 || Test Precision = 68.922|| Test Recall = 87.325


3it [00:21,  7.23s/it]


tensor([[4.0868],
        [4.1514],
        [4.0868],
        ...,
        [3.5696],
        [3.7017],
        [3.4372]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.85      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-110: Loss = 1.796
Train RMSE = 1.352||Train Precision = 70.955||Train Recall = 85.074
Test RMSE = 0.962 || Test Precision = 70.120|| Test Recall = 84.593


3it [00:21,  7.13s/it]


tensor([[4.0409],
        [4.1100],
        [4.0409],
        ...,
        [3.5527],
        [3.7090],
        [3.4646]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-111: Loss = 1.781
Train RMSE = 1.345||Train Precision = 71.489||Train Recall = 83.465
Test RMSE = 0.962 || Test Precision = 70.816|| Test Recall = 82.937


3it [00:21,  7.28s/it]


tensor([[4.0112],
        [4.0872],
        [4.0112],
        ...,
        [3.5258],
        [3.6855],
        [3.3939]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.58      0.64      8765
           1       0.71      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-112: Loss = 1.785
Train RMSE = 1.347||Train Precision = 71.853||Train Recall = 81.546
Test RMSE = 0.963 || Test Precision = 71.371|| Test Recall = 81.344


3it [00:21,  7.30s/it]


tensor([[4.0660],
        [4.1294],
        [4.0660],
        ...,
        [3.5385],
        [3.6887],
        [3.4336]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.55      0.63      8765
           1       0.71      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-113: Loss = 1.784
Train RMSE = 1.347||Train Precision = 70.982||Train Recall = 83.822
Test RMSE = 0.961 || Test Precision = 70.556|| Test Recall = 83.543


3it [00:21,  7.14s/it]


tensor([[4.1475],
        [4.2348],
        [4.1475],
        ...,
        [3.6053],
        [3.7996],
        [3.5354]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.70      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-114: Loss = 1.782
Train RMSE = 1.346||Train Precision = 70.153||Train Recall = 86.941
Test RMSE = 0.962 || Test Precision = 69.523|| Test Recall = 86.213


3it [00:21,  7.28s/it]


tensor([[4.1580],
        [4.2407],
        [4.1580],
        ...,
        [3.6251],
        [3.7845],
        [3.5107]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.51      0.61      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-115: Loss = 1.776
Train RMSE = 1.343||Train Precision = 69.722||Train Recall = 87.304
Test RMSE = 0.962 || Test Precision = 69.324|| Test Recall = 86.756


3it [00:21,  7.29s/it]


tensor([[4.1537],
        [4.2641],
        [4.1537],
        ...,
        [3.5954],
        [3.7866],
        [3.5751]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.51      0.61      8765
           1       0.69      0.87      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-116: Loss = 1.777
Train RMSE = 1.344||Train Precision = 70.076||Train Recall = 87.001
Test RMSE = 0.962 || Test Precision = 69.434|| Test Recall = 86.640


3it [00:21,  7.14s/it]


tensor([[4.1291],
        [4.2576],
        [4.1291],
        ...,
        [3.5579],
        [3.7919],
        [3.5709]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.70      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-117: Loss = 1.771
Train RMSE = 1.341||Train Precision = 70.435||Train Recall = 86.616
Test RMSE = 0.961 || Test Precision = 69.706|| Test Recall = 85.874


3it [00:22,  7.45s/it]


tensor([[4.0643],
        [4.1526],
        [4.0643],
        ...,
        [3.5086],
        [3.7059],
        [3.5203]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.55      0.63      8765
           1       0.71      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-118: Loss = 1.770
Train RMSE = 1.340||Train Precision = 71.592||Train Recall = 84.085
Test RMSE = 0.961 || Test Precision = 70.595|| Test Recall = 83.596


3it [00:21,  7.15s/it]


tensor([[4.0949],
        [4.1897],
        [4.0949],
        ...,
        [3.5103],
        [3.7472],
        [3.5398]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.55      0.62      8765
           1       0.70      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.70     20000
weighted avg       0.71      0.71      0.70     20000

Epoch-119: Loss = 1.765
Train RMSE = 1.339||Train Precision = 71.240||Train Recall = 84.587
Test RMSE = 0.960 || Test Precision = 70.361|| Test Recall = 84.201


3it [00:21,  7.23s/it]


tensor([[4.1260],
        [4.2333],
        [4.1260],
        ...,
        [3.5364],
        [3.7504],
        [3.5411]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.52      0.61      8765
           1       0.70      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-120: Loss = 1.767
Train RMSE = 1.340||Train Precision = 70.212||Train Recall = 87.078
Test RMSE = 0.961 || Test Precision = 69.713|| Test Recall = 85.883


3it [00:21,  7.33s/it]


tensor([[4.1377],
        [4.2453],
        [4.1377],
        ...,
        [3.5492],
        [3.7834],
        [3.5907]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.75      0.51      0.61      8765
           1       0.70      0.86      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-121: Loss = 1.760
Train RMSE = 1.337||Train Precision = 70.142||Train Recall = 87.153
Test RMSE = 0.962 || Test Precision = 69.535|| Test Recall = 86.462


3it [00:21,  7.12s/it]


tensor([[4.0412],
        [4.0885],
        [4.0412],
        ...,
        [3.4707],
        [3.6027],
        [3.3542]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.59      0.65      8765
           1       0.72      0.81      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-122: Loss = 1.767
Train RMSE = 1.340||Train Precision = 73.046||Train Recall = 81.306
Test RMSE = 0.962 || Test Precision = 71.807|| Test Recall = 80.908


3it [00:21,  7.29s/it]


tensor([[4.1257],
        [4.2307],
        [4.1257],
        ...,
        [3.5435],
        [3.7828],
        [3.4845]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.74      0.53      0.62      8765
           1       0.70      0.85      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.69     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-123: Loss = 1.763
Train RMSE = 1.338||Train Precision = 70.572||Train Recall = 85.622
Test RMSE = 0.960 || Test Precision = 69.942|| Test Recall = 85.412


3it [00:21,  7.18s/it]


tensor([[4.1300],
        [4.2246],
        [4.1300],
        ...,
        [3.5340],
        [3.7558],
        [3.4806]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.54      0.62      8765
           1       0.70      0.85      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.69      0.70     20000
weighted avg       0.72      0.71      0.71     20000

Epoch-124: Loss = 1.753
Train RMSE = 1.333||Train Precision = 70.854||Train Recall = 84.962
Test RMSE = 0.959 || Test Precision = 70.339|| Test Recall = 84.726


3it [00:21,  7.16s/it]


tensor([[4.1213],
        [4.2386],
        [4.1213],
        ...,
        [3.5256],
        [3.7547],
        [3.5094]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.73      0.55      0.63      8765
           1       0.71      0.84      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.70      0.70     20000
weighted avg       0.72      0.71      0.71     20000

Epoch-125: Loss = 1.751
Train RMSE = 1.333||Train Precision = 71.410||Train Recall = 84.254
Test RMSE = 0.960 || Test Precision = 70.709|| Test Recall = 83.818


3it [00:22,  7.34s/it]


tensor([[4.0742],
        [4.1811],
        [4.0742],
        ...,
        [3.4899],
        [3.7248],
        [3.4965]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.72      0.56      0.63      8765
           1       0.71      0.83      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.70      0.70     20000
weighted avg       0.72      0.71      0.71     20000

Epoch-126: Loss = 1.749
Train RMSE = 1.332||Train Precision = 71.744||Train Recall = 83.454
Test RMSE = 0.959 || Test Precision = 70.977|| Test Recall = 83.062


3it [00:21,  7.23s/it]


tensor([[4.1615],
        [4.3371],
        [4.1615],
        ...,
        [3.5735],
        [3.8625],
        [3.7186]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.76      0.49      0.59      8765
           1       0.69      0.88      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.72      0.71      0.69     20000

Epoch-127: Loss = 1.751
Train RMSE = 1.333||Train Precision = 69.054||Train Recall = 88.877
Test RMSE = 0.965 || Test Precision = 68.760|| Test Recall = 88.002


3it [00:21,  7.16s/it]


tensor([[3.9250],
        [4.0408],
        [3.9250],
        ...,
        [3.4226],
        [3.6559],
        [3.4853]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.69      0.62      0.66      8765
           1       0.73      0.78      0.75     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.71     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-128: Loss = 1.769
Train RMSE = 1.343||Train Precision = 73.877||Train Recall = 78.524
Test RMSE = 0.966 || Test Precision = 72.700|| Test Recall = 78.478


3it [00:22,  7.34s/it]


tensor([[4.0109],
        [4.1250],
        [4.0109],
        ...,
        [3.4984],
        [3.7142],
        [3.5564]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.71      0.58      0.64      8765
           1       0.71      0.82      0.76     11235

    accuracy                           0.71     20000
   macro avg       0.71      0.70      0.70     20000
weighted avg       0.71      0.71      0.71     20000

Epoch-129: Loss = 1.754
Train RMSE = 1.336||Train Precision = 72.070||Train Recall = 82.516
Test RMSE = 0.961 || Test Precision = 71.488|| Test Recall = 81.656


3it [00:21,  7.13s/it]


tensor([[4.1556],
        [4.3682],
        [4.1556],
        ...,
        [3.5467],
        [3.8709],
        [3.7589]], device='cuda:0')
              precision    recall  f1-score   support

           0       0.76      0.49      0.60      8765
           1       0.69      0.88      0.77     11235

    accuracy                           0.71     20000
   macro avg       0.72      0.68      0.68     20000
weighted avg       0.72      0.71      0.70     20000

Epoch-130: Loss = 1.760
Train RMSE = 1.339||Train Precision = 69.011||Train Recall = 88.762
Test RMSE = 0.963 || Test Precision = 68.876|| Test Recall = 87.850


0it [00:00, ?it/s]

In [ ]:
torch.save(sm_net, "./pretrained/meta.pth")

In [ ]:
import matplotlib.pyplot as plt

plt.plot(train_loss[10::], label = "Train Loss")
plt.plot(test_loss[10::], label = "Test Loss")
plt.legend()
plt.show()
plt.plot(train_f1, label = "Train F1")
plt.plot(test_f1, label = "Test F1")
plt.legend()
plt.show()


# Test

In [ ]:
import matplotlib.pyplot as plt
import torch

In [ ]:
sm_net = torch.load("./pretrained/meta.pth")

In [ ]:
prs = []
rec = []
f1 = []

for i in np.arange(3, 4, 0.1):
    _, p, r, f, _, _, _ = sm_net.evaluate(i)
    prs.append(p)
    rec.append(r)
    f1.append(f)
    
plt.plot(prs, label = "Test Precision")
plt.plot(rec, label = "Test Recall")
plt.plot(f1, label = "Test F1")

plt.legend()
plt.show()

In [ ]:
prs

In [ ]:
rec